package messari

import "time"

type autoGenerated struct {
	Status struct {
		Timestamp time.Time `json:"timestamp" bson:"timestamp"`
		Elapsed   int       `json:"elapsed" bson:"elapsed"`
	} `json:"status" bson:"status"`
	Data []struct {
		ID      string `json:"id" bson:"id"`
		Symbol  string `json:"symbol" bson:"symbol"`
		Name    string `json:"name" bson:"name"`
		Slug    string `json:"slug" bson:"slug"`
		Profile struct {
			Profile struct {
				General struct {
					Overview struct {
						IsVerified     bool   `json:"is_verified" bson:"is_verified"`
						Tagline        string `json:"tagline" bson:"tagline"`
						Category       string `json:"category" bson:"category"`
						Sector         string `json:"sector" bson:"sector"`
						Tags           string `json:"tags" bson:"tags"`
						ProjectDetails string `json:"project_details" bson:"project_details"`
						OfficialLinks  []struct {
							Name string `json:"name" bson:"name"`
							Link string `json:"link" bson:"link"`
						} `json:"official_links" bson:"official_links"`
					} `json:"overview" bson:"overview"`
					Background struct {
						BackgroundDetails    string `json:"background_details" bson:"background_details"`
						IssuingOrganizations []struct {
							Slug        string `json:"slug" bson:"slug"`
							Name        string `json:"name" bson:"name"`
							Logo        string `json:"logo" bson:"logo"`
							Description string `json:"description" bson:"description"`
						} `json:"issuing_organizations" bson:"issuing_organizations"`
					} `json:"background" bson:"background"`
					Roadmap []struct {
						Title   string    `json:"title" bson:"title"`
						Date    time.Time `json:"date" bson:"date"`
						Type    string    `json:"type" bson:"type"`
						Details string    `json:"details" bson:"details"`
					} `json:"roadmap" bson:"roadmap"`
					Regulation struct {
						RegulatoryDetails string `json:"regulatory_details" bson:"regulatory_details"`
						SfarScore         int    `json:"sfar_score" bson:"sfar_score"`
						SfarSummary       string `json:"sfar_summary" bson:"sfar_summary"`
					} `json:"regulation" bson:"regulation"`
				} `json:"general" bson:"general"`
				Contributors struct {
					Individuals []struct {
						Slug        string `json:"slug" bson:"slug"`
						FirstName   string `json:"first_name" bson:"first_name"`
						LastName    string `json:"last_name" bson:"last_name"`
						Title       string `json:"title" bson:"title"`
						Description string `json:"description" bson:"description"`
						AvatarURL   string `json:"avatar_url" bson:"avatar_url"`
					} `json:"individuals" bson:"individuals"`
					Organizations []struct {
						Slug        string `json:"slug" bson:"slug"`
						Name        string `json:"name" bson:"name"`
						Logo        string `json:"logo" bson:"logo"`
						Description string `json:"description" bson:"description"`
					} `json:"organizations" bson:"organizations"`
				} `json:"contributors" bson:"contributors"`
				Advisors struct {
					Individuals []struct {
						Slug        string `json:"slug" bson:"slug"`
						FirstName   string `json:"first_name" bson:"first_name"`
						LastName    string `json:"last_name" bson:"last_name"`
						Title       string `json:"title" bson:"title"`
						Description string `json:"description" bson:"description"`
						AvatarURL   string `json:"avatar_url" bson:"avatar_url"`
					} `json:"individuals" bson:"individuals"`
					Organizations []struct {
						Slug        string `json:"slug" bson:"slug"`
						Name        string `json:"name" bson:"name"`
						Logo        string `json:"logo" bson:"logo"`
						Description string `json:"description" bson:"description"`
					} `json:"organizations" bson:"organizations"`
				} `json:"advisors" bson:"advisors"`
				Investors struct {
					Individuals []struct {
						Slug        string `json:"slug" bson:"slug"`
						FirstName   string `json:"first_name" bson:"first_name"`
						LastName    string `json:"last_name" bson:"last_name"`
						Title       string `json:"title" bson:"title"`
						Description string `json:"description" bson:"description"`
						AvatarURL   string `json:"avatar_url" bson:"avatar_url"`
					} `json:"individuals" bson:"individuals"`
					Organizations []struct {
						Slug        string `json:"slug" bson:"slug"`
						Name        string `json:"name" bson:"name"`
						Logo        string `json:"logo" bson:"logo"`
						Description string `json:"description" bson:"description"`
					} `json:"organizations" bson:"organizations"`
				} `json:"investors" bson:"investors"`
				Ecosystem struct {
					Assets []struct {
						ID   string `json:"id" bson:"id"`
						Name string `json:"name" bson:"name"`
					} `json:"assets" bson:"assets"`
					Organizations []struct {
						Slug        string `json:"slug" bson:"slug"`
						Name        string `json:"name" bson:"name"`
						Logo        string `json:"logo" bson:"logo"`
						Description string `json:"description" bson:"description"`
					} `json:"organizations" bson:"organizations"`
				} `json:"ecosystem" bson:"ecosystem"`
				Economics struct {
					Token struct {
						TokenName      string `json:"token_name" bson:"token_name"`
						TokenType      string `json:"token_type" bson:"token_type"`
						BlockExplorers []struct {
							Name string `json:"name" bson:"name"`
							Link string `json:"link" bson:"link"`
						} `json:"block_explorers" bson:"block_explorers"`
						Multitoken []struct {
							ID   string `json:"id" bson:"id"`
							Name string `json:"name" bson:"name"`
						} `json:"multitoken" bson:"multitoken"`
						TokenUsage                  string `json:"token_usage" bson:"token_usage"`
						TokenUsageDetailsAndWallets string `json:"token_usage_details_and_wallets" bson:"token_usage_details_and_wallets"`
					} `json:"token" bson:"token"`
					Launch struct {
						General struct {
							LaunchStyle   string `json:"launch_style" bson:"launch_style"`
							LaunchDetails string `json:"launch_details" bson:"launch_details"`
						} `json:"general" bson:"general"`
						Fundraising struct {
							SalesRounds []struct {
								RestrictedJurisdictions []interface{} `json:"restricted_jurisdictions" bson:"restricted_jurisdictions"`
							} `json:"sales_rounds" bson:"sales_rounds"`
							SalesDocuments []struct {
							} `json:"sales_documents" bson:"sales_documents"`
							SalesTreasuryAccounts []struct {
							} `json:"sales_treasury_accounts" bson:"sales_treasury_accounts"`
							TreasuryPolicies []struct {
							} `json:"treasury_policies" bson:"treasury_policies"`
							ProjectedUseOfSalesProceeds []struct {
							} `json:"projected_use_of_sales_proceeds" bson:"projected_use_of_sales_proceeds"`
						} `json:"fundraising" bson:"fundraising"`
						InitialDistribution struct {
							InitialSupply            float64 `json:"initial_supply" bson:"initial_supply"`
							InitialSupplyRepartition struct {
								AllocatedToInvestorsPercentage                 float64 `json:"allocated_to_investors_percentage" bson:"allocated_to_investors_percentage"`
								AllocatedToOrganizationOrFoundersPercentage    float64 `json:"allocated_to_organization_or_founders_percentage" bson:"allocated_to_organization_or_founders_percentage"`
								AllocatedToPreminedRewardsOrAirdropsPercentage int     `json:"allocated_to_premined_rewards_or_airdrops_percentage" bson:"allocated_to_premined_rewards_or_airdrops_percentage"`
							} `json:"initial_supply_repartition" bson:"initial_supply_repartition"`
							TokenDistributionDate time.Time `json:"token_distribution_date" bson:"token_distribution_date"`
							GenesisBlockDate      time.Time `json:"genesis_block_date" bson:"genesis_block_date"`
						} `json:"initial_distribution" bson:"initial_distribution"`
					} `json:"launch" bson:"launch"`
					ConsensusAndEmission struct {
						Supply struct {
							SupplyCurveDetails  string `json:"supply_curve_details" bson:"supply_curve_details"`
							GeneralEmissionType string `json:"general_emission_type" bson:"general_emission_type"`
							PreciseEmissionType string `json:"precise_emission_type" bson:"precise_emission_type"`
							IsCappedSupply      bool   `json:"is_capped_supply" bson:"is_capped_supply"`
							MaxSupply           int    `json:"max_supply" bson:"max_supply"`
						} `json:"supply" bson:"supply"`
						Consensus struct {
							ConsensusDetails          string    `json:"consensus_details" bson:"consensus_details"`
							GeneralConsensusMechanism string    `json:"general_consensus_mechanism" bson:"general_consensus_mechanism"`
							PreciseConsensusMechanism string    `json:"precise_consensus_mechanism" bson:"precise_consensus_mechanism"`
							TargetedBlockTime         int       `json:"targeted_block_time" bson:"targeted_block_time"`
							BlockReward               int       `json:"block_reward" bson:"block_reward"`
							MiningAlgorithm           string    `json:"mining_algorithm" bson:"mining_algorithm"`
							NextHalvingDate           time.Time `json:"next_halving_date" bson:"next_halving_date"`
							IsVictimOf51PercentAttack bool      `json:"is_victim_of_51_percent_attack" bson:"is_victim_of_51_percent_attack"`
						} `json:"consensus" bson:"consensus"`
					} `json:"consensus_and_emission" bson:"consensus_and_emission"`
					NativeTreasury struct {
						Accounts []struct {
							AccountType string `json:"account_type" bson:"account_type"`
							Addresses   []struct {
							} `json:"addresses" bson:"addresses"`
						} `json:"accounts" bson:"accounts"`
						TreasuryUsageDetails string `json:"treasury_usage_details" bson:"treasury_usage_details"`
					} `json:"native_treasury" bson:"native_treasury"`
				} `json:"economics" bson:"economics"`
				Technology struct {
					Overview struct {
						TechnologyDetails  string `json:"technology_details" bson:"technology_details"`
						ClientRepositories []struct {
							Name        string `json:"name" bson:"name"`
							Link        string `json:"link" bson:"link"`
							LicenseType string `json:"license_type" bson:"license_type"`
						} `json:"client_repositories" bson:"client_repositories"`
					} `json:"overview" bson:"overview"`
					Security struct {
						Audits []struct {
							Title   string    `json:"title" bson:"title"`
							Date    time.Time `json:"date" bson:"date"`
							Type    string    `json:"type" bson:"type"`
							Details string    `json:"details" bson:"details"`
						} `json:"audits" bson:"audits"`
						KnownExploitsAndVulnerabilities []struct {
							Title   string    `json:"title" bson:"title"`
							Date    time.Time `json:"date" bson:"date"`
							Type    string    `json:"type" bson:"type"`
							Details string    `json:"details" bson:"details"`
						} `json:"known_exploits_and_vulnerabilities" bson:"known_exploits_and_vulnerabilities"`
					} `json:"security" bson:"security"`
				} `json:"technology" bson:"technology"`
				Governance struct {
					GovernanceDetails string `json:"governance_details" bson:"governance_details"`
					OnchainGovernance struct {
						OnchainGovernanceType    string `json:"onchain_governance_type" bson:"onchain_governance_type"`
						OnchainGovernanceDetails string `json:"onchain_governance_details" bson:"onchain_governance_details"`
						IsTreasuryDecentralized  bool   `json:"is_treasury_decentralized" bson:"is_treasury_decentralized"`
					} `json:"onchain_governance" bson:"onchain_governance"`
					Grants []struct {
						FundingOrganizations []struct {
						} `json:"funding_organizations" bson:"funding_organizations"`
						GrantProgramDetails string `json:"grant_program_details" bson:"grant_program_details"`
					} `json:"grants" bson:"grants"`
				} `json:"governance" bson:"governance"`
			} `json:"profile" bson:"profile"`
		} `json:"profile" bson:"profile"`
		Metrics struct {
			ID         string `json:"id" bson:"id"`
			Symbol     string `json:"symbol" bson:"symbol"`
			Name       string `json:"name" bson:"name"`
			Slug       string `json:"slug" bson:"slug"`
			MarketData struct {
				PriceUsd                               float64 `json:"price_usd" bson:"price_usd"`
				PriceBtc                               int     `json:"price_btc" bson:"price_btc"`
				VolumeLast24Hours                      float64 `json:"volume_last_24_hours" bson:"volume_last_24_hours"`
				RealVolumeLast24Hours                  float64 `json:"real_volume_last_24_hours" bson:"real_volume_last_24_hours"`
				VolumeLast24HoursOverstatementMultiple float64 `json:"volume_last_24_hours_overstatement_multiple" bson:"volume_last_24_hours_overstatement_multiple"`
				PercentChangeUsdLast24Hours            float64 `json:"percent_change_usd_last_24_hours" bson:"percent_change_usd_last_24_hours"`
				PercentChangeBtcLast24Hours            int     `json:"percent_change_btc_last_24_hours" bson:"percent_change_btc_last_24_hours"`
				OhlcvLast1Hour                         struct {
					Open   float64 `json:"open" bson:"open"`
					High   float64 `json:"high" bson:"high"`
					Low    float64 `json:"low" bson:"low"`
					Close  float64 `json:"close" bson:"close"`
					Volume float64 `json:"volume" bson:"volume"`
				} `json:"ohlcv_last_1_hour" bson:"ohlcv_last_1_hour"`
				OhlcvLast24Hour struct {
					Open   float64 `json:"open" bson:"open"`
					High   float64 `json:"high" bson:"high"`
					Low    float64 `json:"low" bson:"low"`
					Close  float64 `json:"close" bson:"close"`
					Volume float64 `json:"volume" bson:"volume"`
				} `json:"ohlcv_last_24_hour" bson:"ohlcv_last_24_hour"`
			} `json:"market_data" bson:"market_data"`
			Supply struct {
				Y2050                float64 `json:"y_2050" bson:"y_2050"`
				Y2050PercentIssued   int     `json:"y_2050_percent_issued" bson:"y_2050_percent_issued"`
				SupplyYplus10        float64 `json:"supply_yplus_10" bson:"supply_yplus_10"`
				YPlus10IssuedPercent int     `json:"y_plus10_issued_percent" bson:"y_plus_10_issued_percent"`
				Liquid               int     `json:"liquid" bson:"liquid"`
				Circulating          int     `json:"circulating" bson:"circulating"`
				StockToFlow          int     `json:"stock_to_flow" bson:"stock_to_flow"`
			} `json:"supply" bson:"supply"`
			BlockchainStats24Hours struct {
				TransactionVolume      float64     `json:"transaction_volume" bson:"transaction_volume"`
				Nvt                    float64     `json:"nvt" bson:"nvt"`
				SumOfFees              float64     `json:"sum_of_fees" bson:"sum_of_fees"`
				MedianTxValue          float64     `json:"median_tx_value" bson:"median_tx_value"`
				MedianTxFee            float64     `json:"median_tx_fee" bson:"median_tx_fee"`
				CountOfActiveAddresses int         `json:"count_of_active_addresses" bson:"count_of_active_addresses"`
				CountOfTx              int         `json:"count_of_tx" bson:"count_of_tx"`
				CountOfPayments        int         `json:"count_of_payments" bson:"count_of_payments"`
				NewIssuance            float64     `json:"new_issuance" bson:"new_issuance"`
				AverageDifficulty      int64       `json:"average_difficulty" bson:"average_difficulty"`
				KilobytesAdded         float64     `json:"kilobytes_added" bson:"kilobytes_added"`
				CountOfBlocksAdded     int         `json:"count_of_blocks_added" bson:"count_of_blocks_added"`
				SupplyMovedOffChain    interface{} `json:"supply_moved_off_chain" bson:"supply_moved_off_chain"`
			} `json:"blockchain_stats_24_hours" bson:"blockchain_stats_24_hours"`
			AllTimeHigh struct {
				Price       int       `json:"price" bson:"price"`
				At          time.Time `json:"at" bson:"at"`
				DaysSince   int       `json:"days_since" bson:"days_since"`
				PercentDown float64   `json:"percent_down" bson:"percent_down"`
			} `json:"all_time_high" bson:"all_time_high"`
			DeveloperActivity struct {
				Stars                   int `json:"stars" bson:"stars"`
				Watchers                int `json:"watchers" bson:"watchers"`
				CommitsLast3Months      int `json:"commits_last_3_months" bson:"commits_last_3_months"`
				CommitsLast1Year        int `json:"commits_last_1_year" bson:"commits_last_1_year"`
				LinesAddedLast3Months   int `json:"lines_added_last_3_months" bson:"lines_added_last_3_months"`
				LinesAddedLast1Year     int `json:"lines_added_last_1_year" bson:"lines_added_last_1_year"`
				LinesDeletedLast3Months int `json:"lines_deleted_last_3_months" bson:"lines_deleted_last_3_months"`
				LinesDeletedLast1Year   int `json:"lines_deleted_last_1_year" bson:"lines_deleted_last_1_year"`
			} `json:"developer_activity" bson:"developer_activity"`
			RoiData struct {
				PercentChangeLast1Week   float64 `json:"percent_change_last_1_week" bson:"percent_change_last_1_week"`
				PercentChangeLast1Month  float64 `json:"percent_change_last_1_month" bson:"percent_change_last_1_month"`
				PercentChangeLast3Months float64 `json:"percent_change_last_3_months" bson:"percent_change_last_3_months"`
				PercentChangeLast1Year   float64 `json:"percent_change_last_1_year" bson:"percent_change_last_1_year"`
			} `json:"roi_data" bson:"roi_data"`
			MiscData struct {
				AssetAgeDays     int        `json:"asset_age_days" bson:"asset_age_days"`
				VladimirClubCost float64    `json:"vladimir_club_cost" bson:"vladimir_club_cost"`
				Categories       [][]string `json:"categories" bson:"categories"`
				Sector           [][]string `json:"sector" bson:"sector"`
			} `json:"misc_data" bson:"misc_data"`
		} `json:"metrics" bson:"metrics"`
	} `json:"data" bson:"data"`
}

// Asset Profile V2
type assetProfile struct {
	Status struct {
		Timestamp time.Time `json:"timestamp" bson:"timestamp"`
		Elapsed   int       `json:"elapsed" bson:"elapsed"`
	} `json:"status" bson:"status"`
	Data struct {
		Profile struct {
			General struct {
				Overview struct {
					IsVerified     bool   `json:"is_verified" bson:"is_verified"`
					Tagline        string `json:"tagline" bson:"tagline"`
					Category       string `json:"category" bson:"category"`
					Sector         string `json:"sector" bson:"sector"`
					Tags           string `json:"tags" bson:"tags"`
					ProjectDetails string `json:"project_details" bson:"project_details"`
					OfficialLinks  []struct {
						Name string `json:"name" bson:"name"`
						Link string `json:"link" bson:"link"`
					} `json:"official_links" bson:"official_links"`
				} `json:"overview" bson:"overview"`
				Background struct {
					BackgroundDetails    string `json:"background_details" bson:"background_details"`
					IssuingOrganizations []struct {
						Slug        string `json:"slug" bson:"slug"`
						Name        string `json:"name" bson:"name"`
						Logo        string `json:"logo" bson:"logo"`
						Description string `json:"description" bson:"description"`
					} `json:"issuing_organizations" bson:"issuing_organizations"`
				} `json:"background" bson:"background"`
				Roadmap []struct {
					Title   string    `json:"title" bson:"title"`
					Date    time.Time `json:"date" bson:"date"`
					Type    string    `json:"type" bson:"type"`
					Details string    `json:"details" bson:"details"`
				} `json:"roadmap" bson:"roadmap"`
				Regulation struct {
					RegulatoryDetails string `json:"regulatory_details" bson:"regulatory_details"`
					SfarScore         int    `json:"sfar_score" bson:"sfar_score"`
					SfarSummary       string `json:"sfar_summary" bson:"sfar_summary"`
				} `json:"regulation" bson:"regulation"`
			} `json:"general" bson:"general"`
			Contributors struct {
				Individuals []struct {
					Slug        string `json:"slug" bson:"slug"`
					FirstName   string `json:"first_name" bson:"first_name"`
					LastName    string `json:"last_name" bson:"last_name"`
					Title       string `json:"title" bson:"title"`
					Description string `json:"description" bson:"description"`
					AvatarURL   string `json:"avatar_url" bson:"avatar_url"`
				} `json:"individuals" bson:"individuals"`
				Organizations []struct {
					Slug        string `json:"slug" bson:"slug"`
					Name        string `json:"name" bson:"name"`
					Logo        string `json:"logo" bson:"logo"`
					Description string `json:"description" bson:"description"`
				} `json:"organizations" bson:"organizations"`
			} `json:"contributors" bson:"contributors"`
			Advisors struct {
				Individuals []struct {
					Slug        string `json:"slug" bson:"slug"`
					FirstName   string `json:"first_name" bson:"first_name"`
					LastName    string `json:"last_name" bson:"last_name"`
					Title       string `json:"title" bson:"title"`
					Description string `json:"description" bson:"description"`
					AvatarURL   string `json:"avatar_url" bson:"avatar_url"`
				} `json:"individuals" bson:"individuals"`
				Organizations []struct {
					Slug        string `json:"slug" bson:"slug"`
					Name        string `json:"name" bson:"name"`
					Logo        string `json:"logo" bson:"logo"`
					Description string `json:"description" bson:"description"`
				} `json:"organizations" bson:"organizations"`
			} `json:"advisors" bson:"advisors"`
			Investors struct {
				Individuals []struct {
					Slug        string `json:"slug" bson:"slug"`
					FirstName   string `json:"first_name" bson:"first_name"`
					LastName    string `json:"last_name" bson:"last_name"`
					Title       string `json:"title" bson:"title"`
					Description string `json:"description" bson:"description"`
					AvatarURL   string `json:"avatar_url" bson:"avatar_url"`
				} `json:"individuals" bson:"individuals"`
				Organizations []struct {
					Slug        string `json:"slug" bson:"slug"`
					Name        string `json:"name" bson:"name"`
					Logo        string `json:"logo" bson:"logo"`
					Description string `json:"description" bson:"description"`
				} `json:"organizations" bson:"organizations"`
			} `json:"investors" bson:"investors"`
			Ecosystem struct {
				Assets []struct {
					ID   string `json:"id" bson:"id"`
					Name string `json:"name" bson:"name"`
				} `json:"assets" bson:"assets"`
				Organizations []struct {
					Slug        string `json:"slug" bson:"slug"`
					Name        string `json:"name" bson:"name"`
					Logo        string `json:"logo" bson:"logo"`
					Description string `json:"description" bson:"description"`
				} `json:"organizations" bson:"organizations"`
			} `json:"ecosystem" bson:"ecosystem"`
			Economics struct {
				Token struct {
					TokenName      string `json:"token_name" bson:"token_name"`
					TokenType      string `json:"token_type" bson:"token_type"`
					BlockExplorers []struct {
						Name string `json:"name" bson:"name"`
						Link string `json:"link" bson:"link"`
					} `json:"block_explorers" bson:"block_explorers"`
					Multitoken []struct {
						ID   string `json:"id" bson:"id"`
						Name string `json:"name" bson:"name"`
					} `json:"multitoken" bson:"multitoken"`
					TokenUsage                  string `json:"token_usage" bson:"token_usage"`
					TokenUsageDetailsAndWallets string `json:"token_usage_details_and_wallets" bson:"token_usage_details_and_wallets"`
				} `json:"token" bson:"token"`
				Launch struct {
					General struct {
						LaunchStyle   string `json:"launch_style" bson:"launch_style"`
						LaunchDetails string `json:"launch_details" bson:"launch_details"`
					} `json:"general" bson:"general"`
					Fundraising struct {
						SalesRounds []struct {
							Title                        string    `json:"title" bson:"title"`
							StartDate                    time.Time `json:"start_date" bson:"start_date"`
							Type                         string    `json:"type" bson:"type"`
							Details                      string    `json:"details" bson:"details"`
							EndDate                      time.Time `json:"end_date" bson:"end_date"`
							NativeTokensAllocated        int       `json:"native_tokens_allocated" bson:"native_tokens_allocated"`
							AssetCollected               string    `json:"asset_collected" bson:"asset_collected"`
							PricePerTokenInAsset         float64   `json:"price_per_token_in_asset" bson:"price_per_token_in_asset"`
							EquivalentPricePerTokenInUSD float64   `json:"equivalent_price_per_token_in_USD" bson:"equivalent_price_per_token_in_usd"`
							AmountCollectedInAsset       int       `json:"amount_collected_in_asset" bson:"amount_collected_in_asset"`
							AmountCollectedInUSD         int       `json:"amount_collected_in_USD" bson:"amount_collected_in_usd"`
							IsKycRequired                bool      `json:"is_kyc_required" bson:"is_kyc_required"`
							RestrictedJurisdictions      []string  `json:"restricted_jurisdictions" bson:"restricted_jurisdictions"`
						} `json:"sales_rounds" bson:"sales_rounds"`
						SalesDocuments []struct {
							Name string `json:"name" bson:"name"`
							Link string `json:"link" bson:"link"`
						} `json:"sales_documents" bson:"sales_documents"`
						SalesTreasuryAccounts []struct {
							AccountType string `json:"account_type" bson:"account_type"`
							AssetHeld   struct {
								ID   string `json:"id" bson:"id"`
								Name string `json:"name" bson:"name"`
							} `json:"asset_held" bson:"asset_held"`
							Addresses []struct {
							} `json:"addresses" bson:"addresses"`
							Security string `json:"security" bson:"security"`
						} `json:"sales_treasury_accounts" bson:"sales_treasury_accounts"`
						TreasuryPolicies []struct {
							Name string `json:"name" bson:"name"`
							Link string `json:"link" bson:"link"`
						} `json:"treasury_policies" bson:"treasury_policies"`
						ProjectedUseOfSalesProceeds []struct {
							Category           string  `json:"category" bson:"category"`
							AmountInPercentage float64 `json:"amount_in_percentage" bson:"amount_in_percentage"`
						} `json:"projected_use_of_sales_proceeds" bson:"projected_use_of_sales_proceeds"`
					} `json:"fundraising" bson:"fundraising"`
					InitialDistribution struct {
						InitialSupply            float64 `json:"initial_supply" bson:"initial_supply"`
						InitialSupplyRepartition struct {
							AllocatedToInvestorsPercentage                 float64 `json:"allocated_to_investors_percentage" bson:"allocated_to_investors_percentage"`
							AllocatedToOrganizationOrFoundersPercentage    float64 `json:"allocated_to_organization_or_founders_percentage" bson:"allocated_to_organization_or_founders_percentage"`
							AllocatedToPreminedRewardsOrAirdropsPercentage int     `json:"allocated_to_premined_rewards_or_airdrops_percentage" bson:"allocated_to_premined_rewards_or_airdrops_percentage"`
						} `json:"initial_supply_repartition" bson:"initial_supply_repartition"`
						TokenDistributionDate time.Time `json:"token_distribution_date" bson:"token_distribution_date"`
						GenesisBlockDate      time.Time `json:"genesis_block_date" bson:"genesis_block_date"`
					} `json:"initial_distribution" bson:"initial_distribution"`
				} `json:"launch" bson:"launch"`
				ConsensusAndEmission struct {
					Supply struct {
						SupplyCurveDetails  string `json:"supply_curve_details" bson:"supply_curve_details"`
						GeneralEmissionType string `json:"general_emission_type" bson:"general_emission_type"`
						PreciseEmissionType string `json:"precise_emission_type" bson:"precise_emission_type"`
						IsCappedSupply      bool   `json:"is_capped_supply" bson:"is_capped_supply"`
						MaxSupply           int    `json:"max_supply" bson:"max_supply"`
					} `json:"supply" bson:"supply"`
					Consensus struct {
						ConsensusDetails          string    `json:"consensus_details" bson:"consensus_details"`
						GeneralConsensusMechanism string    `json:"general_consensus_mechanism" bson:"general_consensus_mechanism"`
						PreciseConsensusMechanism string    `json:"precise_consensus_mechanism" bson:"precise_consensus_mechanism"`
						TargetedBlockTime         int       `json:"targeted_block_time" bson:"targeted_block_time"`
						BlockReward               int       `json:"block_reward" bson:"block_reward"`
						MiningAlgorithm           string    `json:"mining_algorithm" bson:"mining_algorithm"`
						NextHalvingDate           time.Time `json:"next_halving_date" bson:"next_halving_date"`
						IsVictimOf51PercentAttack bool      `json:"is_victim_of_51_percent_attack" bson:"is_victim_of_51_percent_attack"`
					} `json:"consensus" bson:"consensus"`
				} `json:"consensus_and_emission" bson:"consensus_and_emission"`
				NativeTreasury struct {
					Accounts []struct {
						AccountType string `json:"account_type" bson:"account_type"`
						Addresses   []struct {
							Name string `json:"name" bson:"name"`
							Link string `json:"link" bson:"link"`
						} `json:"addresses" bson:"addresses"`
					} `json:"accounts" bson:"accounts"`
					TreasuryUsageDetails string `json:"treasury_usage_details" bson:"treasury_usage_details"`
				} `json:"native_treasury" bson:"native_treasury"`
			} `json:"economics" bson:"economics"`
			Technology struct {
				Overview struct {
					TechnologyDetails  string `json:"technology_details" bson:"technology_details"`
					ClientRepositories []struct {
						Name        string `json:"name" bson:"name"`
						Link        string `json:"link" bson:"link"`
						LicenseType string `json:"license_type" bson:"license_type"`
					} `json:"client_repositories" bson:"client_repositories"`
				} `json:"overview" bson:"overview"`
				Security struct {
					Audits []struct {
						Title   string    `json:"title" bson:"title"`
						Date    time.Time `json:"date" bson:"date"`
						Type    string    `json:"type" bson:"type"`
						Details string    `json:"details" bson:"details"`
					} `json:"audits" bson:"audits"`
					KnownExploitsAndVulnerabilities []struct {
						Title   string    `json:"title" bson:"title"`
						Date    time.Time `json:"date" bson:"date"`
						Type    string    `json:"type" bson:"type"`
						Details string    `json:"details" bson:"details"`
					} `json:"known_exploits_and_vulnerabilities" bson:"known_exploits_and_vulnerabilities"`
				} `json:"security" bson:"security"`
			} `json:"technology" bson:"technology"`
			Governance struct {
				GovernanceDetails string `json:"governance_details" bson:"governance_details"`
				OnchainGovernance struct {
					OnchainGovernanceType    string `json:"onchain_governance_type" bson:"onchain_governance_type"`
					OnchainGovernanceDetails string `json:"onchain_governance_details" bson:"onchain_governance_details"`
					IsTreasuryDecentralized  bool   `json:"is_treasury_decentralized" bson:"is_treasury_decentralized"`
				} `json:"onchain_governance" bson:"onchain_governance"`
				Grants []struct {
					FundingOrganizations []struct {
						Slug        string `json:"slug" bson:"slug"`
						Name        string `json:"name" bson:"name"`
						Logo        string `json:"logo" bson:"logo"`
						Description string `json:"description" bson:"description"`
					} `json:"funding_organizations" bson:"funding_organizations"`
					GrantProgramDetails string `json:"grant_program_details" bson:"grant_program_details"`
				} `json:"grants" bson:"grants"`
			} `json:"governance" bson:"governance"`
		} `json:"profile" bson:"profile"`
	} `json:"data" bson:"data"`
}

// Asset Metrics
type assetMetrics struct {
	Status struct {
		Timestamp time.Time `json:"timestamp" bson:"timestamp"`
		Elapsed   int       `json:"elapsed" bson:"elapsed"`
	} `json:"status" bson:"status"`
	Data struct {
		ID         string `json:"id" bson:"id"`
		Symbol     string `json:"symbol" bson:"symbol"`
		Name       string `json:"name" bson:"name"`
		Slug       string `json:"slug" bson:"slug"`
		MarketData struct {
			PriceUsd                               float64 `json:"price_usd" bson:"price_usd"`
			PriceBtc                               int     `json:"price_btc" bson:"price_btc"`
			VolumeLast24Hours                      float64 `json:"volume_last_24_hours" bson:"volume_last_24_hours"`
			RealVolumeLast24Hours                  float64 `json:"real_volume_last_24_hours" bson:"real_volume_last_24_hours"`
			VolumeLast24HoursOverstatementMultiple float64 `json:"volume_last_24_hours_overstatement_multiple" bson:"volume_last_24_hours_overstatement_multiple"`
			PercentChangeUsdLast24Hours            float64 `json:"percent_change_usd_last_24_hours" bson:"percent_change_usd_last_24_hours"`
			PercentChangeBtcLast24Hours            int     `json:"percent_change_btc_last_24_hours" bson:"percent_change_btc_last_24_hours"`
			OhlcvLast1Hour                         struct {
				Open   float64 `json:"open" bson:"open"`
				High   float64 `json:"high" bson:"high"`
				Low    float64 `json:"low" bson:"low"`
				Close  float64 `json:"close" bson:"close"`
				Volume float64 `json:"volume" bson:"volume"`
			} `json:"ohlcv_last_1_hour" bson:"ohlcv_last_1_hour"`
			OhlcvLast24Hour struct {
				Open   float64 `json:"open" bson:"open"`
				High   float64 `json:"high" bson:"high"`
				Low    float64 `json:"low" bson:"low"`
				Close  float64 `json:"close" bson:"close"`
				Volume float64 `json:"volume" bson:"volume"`
			} `json:"ohlcv_last_24_hour" bson:"ohlcv_last_24_hour"`
		} `json:"market_data" bson:"market_data"`
		Supply struct {
			Y2050                float64 `json:"y_2050" bson:"y_2050"`
			Y2050PercentIssued   int     `json:"y_2050_percent_issued" bson:"y_2050_percent_issued"`
			SupplyYplus10        float64 `json:"supply_yplus_10" bson:"supply_yplus_10"`
			YPlus10IssuedPercent int     `json:"y_plus10_issued_percent" bson:"y_plus_10_issued_percent"`
			Liquid               int     `json:"liquid" bson:"liquid"`
			Circulating          int     `json:"circulating" bson:"circulating"`
			StockToFlow          int     `json:"stock_to_flow" bson:"stock_to_flow"`
		} `json:"supply" bson:"supply"`
		BlockchainStats24Hours struct {
			TransactionVolume      float64     `json:"transaction_volume" bson:"transaction_volume"`
			Nvt                    float64     `json:"nvt" bson:"nvt"`
			SumOfFees              float64     `json:"sum_of_fees" bson:"sum_of_fees"`
			MedianTxValue          float64     `json:"median_tx_value" bson:"median_tx_value"`
			MedianTxFee            float64     `json:"median_tx_fee" bson:"median_tx_fee"`
			CountOfActiveAddresses int         `json:"count_of_active_addresses" bson:"count_of_active_addresses"`
			CountOfTx              int         `json:"count_of_tx" bson:"count_of_tx"`
			CountOfPayments        int         `json:"count_of_payments" bson:"count_of_payments"`
			NewIssuance            float64     `json:"new_issuance" bson:"new_issuance"`
			AverageDifficulty      int64       `json:"average_difficulty" bson:"average_difficulty"`
			KilobytesAdded         float64     `json:"kilobytes_added" bson:"kilobytes_added"`
			CountOfBlocksAdded     int         `json:"count_of_blocks_added" bson:"count_of_blocks_added"`
			SupplyMovedOffChain    interface{} `json:"supply_moved_off_chain" bson:"supply_moved_off_chain"`
		} `json:"blockchain_stats_24_hours" bson:"blockchain_stats_24_hours"`
		AllTimeHigh struct {
			Price       int       `json:"price" bson:"price"`
			At          time.Time `json:"at" bson:"at"`
			DaysSince   int       `json:"days_since" bson:"days_since"`
			PercentDown float64   `json:"percent_down" bson:"percent_down"`
		} `json:"all_time_high" bson:"all_time_high"`
		DeveloperActivity struct {
			Stars                   int `json:"stars" bson:"stars"`
			Watchers                int `json:"watchers" bson:"watchers"`
			CommitsLast3Months      int `json:"commits_last_3_months" bson:"commits_last_3_months"`
			CommitsLast1Year        int `json:"commits_last_1_year" bson:"commits_last_1_year"`
			LinesAddedLast3Months   int `json:"lines_added_last_3_months" bson:"lines_added_last_3_months"`
			LinesAddedLast1Year     int `json:"lines_added_last_1_year" bson:"lines_added_last_1_year"`
			LinesDeletedLast3Months int `json:"lines_deleted_last_3_months" bson:"lines_deleted_last_3_months"`
			LinesDeletedLast1Year   int `json:"lines_deleted_last_1_year" bson:"lines_deleted_last_1_year"`
		} `json:"developer_activity" bson:"developer_activity"`
		RoiData struct {
			PercentChangeLast1Week   float64 `json:"percent_change_last_1_week" bson:"percent_change_last_1_week"`
			PercentChangeLast1Month  float64 `json:"percent_change_last_1_month" bson:"percent_change_last_1_month"`
			PercentChangeLast3Months float64 `json:"percent_change_last_3_months" bson:"percent_change_last_3_months"`
			PercentChangeLast1Year   float64 `json:"percent_change_last_1_year" bson:"percent_change_last_1_year"`
		} `json:"roi_data" bson:"roi_data"`
		MiscData struct {
			AssetAgeDays     int        `json:"asset_age_days" bson:"asset_age_days"`
			VladimirClubCost float64    `json:"vladimir_club_cost" bson:"vladimir_club_cost"`
			Categories       [][]string `json:"categories" bson:"categories"`
			Sector           [][]string `json:"sector" bson:"sector"`
		} `json:"misc_data" bson:"misc_data"`
	} `json:"data" bson:"data"`
}

// Asset Market data
type assetMarketData struct {
	Status struct {
		Timestamp time.Time `json:"timestamp" bson:"timestamp"`
		Elapsed   int       `json:"elapsed" bson:"elapsed"`
	} `json:"status" bson:"status"`
	Data struct {
		ID         string `json:"id" bson:"id"`
		Symbol     string `json:"symbol" bson:"symbol"`
		Name       string `json:"name" bson:"name"`
		Slug       string `json:"slug" bson:"slug"`
		MarketData struct {
			PriceUsd                               float64 `json:"price_usd" bson:"price_usd"`
			PriceBtc                               int     `json:"price_btc" bson:"price_btc"`
			VolumeLast24Hours                      float64 `json:"volume_last_24_hours" bson:"volume_last_24_hours"`
			RealVolumeLast24Hours                  float64 `json:"real_volume_last_24_hours" bson:"real_volume_last_24_hours"`
			VolumeLast24HoursOverstatementMultiple float64 `json:"volume_last_24_hours_overstatement_multiple" bson:"volume_last_24_hours_overstatement_multiple"`
			PercentChangeUsdLast24Hours            float64 `json:"percent_change_usd_last_24_hours" bson:"percent_change_usd_last_24_hours"`
			PercentChangeBtcLast24Hours            int     `json:"percent_change_btc_last_24_hours" bson:"percent_change_btc_last_24_hours"`
			OhlcvLast1Hour                         struct {
				Open   float64 `json:"open" bson:"open"`
				High   float64 `json:"high" bson:"high"`
				Low    float64 `json:"low" bson:"low"`
				Close  float64 `json:"close" bson:"close"`
				Volume float64 `json:"volume" bson:"volume"`
			} `json:"ohlcv_last_1_hour" bson:"ohlcv_last_1_hour"`
			OhlcvLast24Hour struct {
				Open   float64 `json:"open" bson:"open"`
				High   float64 `json:"high" bson:"high"`
				Low    float64 `json:"low" bson:"low"`
				Close  float64 `json:"close" bson:"close"`
				Volume float64 `json:"volume" bson:"volume"`
			} `json:"ohlcv_last_24_hour" bson:"ohlcv_last_24_hour"`
		} `json:"market_data" bson:"market_data"`
	} `json:"data" bson:"data"`
}
